version: '3'
services: 
    mongo:
        image: 'mongo:latest'
        restart: always
    server:
        build:
            dockerfile: Dockerfile
            context: .
        volumes: 
            - /app/node_modules
            - ./: /app
        environment:
            - MONGO_INITDB_ROOT_USERNAME: root
            - MONGO_INITDB_ROOT_PASSWORD: example