version: "3"
services:
  mongo:
    image: "mongo:latest"
    restart: always
  server:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - ./: /app
    environment:
      - MONGO_URI: 'mongodb+srv://halaqaat:Islam123@cluster0.l8yuu.mongodb.net'
      - MONGO_DB_NAME: assetly
